### ISSUE TITLE
switch to globalsign/mgo

### ISSUE THREAD

**Issue by dalu** [256dpi/fire#5]
gopkg.in/mgo is abandoned, no longer maintained
the community supported mgo driver is https://github.com/globalsign/mgo

**Comment by 256dpi** [comment]
Yes! I was thinking about this a couple of times. Do you have time to submit a PR?

**Comment by dalu** [comment]
I don't know how that works to be honest. I can easily edit here on github, but creating a pull request over multiple files is alien to me.

assuming you have 1 path in GOPATH
```bash
cd $GOPATH/src/github.com/256dpi/fire/
for f in `find ./ -type f -iname '*.go'`; do sed -i 's~gopkg.in/mgo.v2~globalsign.com/mgo~' "$f"; done
```

all that's left is 

```
grep 'gopkg.in/mgo' * -R                                  
go.mod:	gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528
go.sum:gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528 h1:/saqWwm73dLmuzbNhe92F0QsZ/KiFND+esHco2v1hiY=
go.sum:gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528/go.mod h1:yeKp02qBN3iKW1OzL3MGk2IdtZzaj7SFntXj72NppTA=
```
go.mod and go.sum

**Comment by 256dpi** [comment]
Done in `v0.16.0`.
